sudo: required
dist: trusty
language: python
python:
  - 3.4

before_install:
  - sudo apt-get update -q || true
  - sudo apt-get install clang-format-3.8 -y

script:
  - cd wpiformat
  - python3 setup.py build
  - python3 setup.py install --optimize=1 --skip-build
  - python3 setup.py test
  - cd .. && python3 -m wpiformat -v
  - git --no-pager diff --exit-code HEAD  # Ensure formatter made no changes
